version: '2'
services:
  front:
    image: mrzizik/front
    ports:
      - "80:80"
    depends_on:
     - node_1
     - node_2
     - node_3
  node_1:
    image: mrzizik/back
    depends_on:
     - mongo
  node_2:
    image: mrzizik/back
    depends_on:
     - mongo
  node_3:
    image: mrzizik/back
    depends_on:
     - mongo
  mongo:
    image: mongo
  redis:
    image: redis
    